Django projet 3/myapp2/app1/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('home', views.home, name='home'),
    path('room', views.room, name='room'),
    path('room1', views.room1, name='room1'),
    path('room2', views.room2, name='room2'),
    path('room3', views.room3, name='room3'),
    path('room4', views.room4, name='room4'),
    path('room5', views.room5, name='room5'),
    path('room6', views.room6, name='room6'),
    path('', views.user_login, name='user_login'),  # Burada 'name' parametresini ekledim
    path('kayıt', views.user_register,name='user_register'),
    path('rezervasyon_oluştur', views.create_reservation,name='create_reservation'),
    path('liste', views.user_register,name='reservation_list'),
    path('iptal', views.user_register,name='cancel_reservation'),
]

Django projet 3/myapp2/myapp2/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('app1.urls')),
]

Django projet 3/myapp2/app1/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
#kayıt için register modeli
class Register(models.Model):
    fırst_name=models.CharField(max_length=30)
    email=models.EmailField(max_length=254, unique=True)
    password=models.CharField(max_length=128)
    
    def save(self, *args, **kwargs):
        # Şifreyi kaydetmeden önce hashle
        if self.password:
            self.password = make_password(self.password)
        super(Register, self).save(*args, **kwargs)
    def __str__(self):
        return self.first_name
#rezervasyon sistemi modeli 
class Reservation(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    check_in=models.DateField()
    check_out=models.DateField()
    room_number=models.IntegerField()
    created_at=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"Rezarvasyo{self.user.username} için {self.check_in}-{self.check_out}"
    

Django projet 3/myapp2/app1/forms.py
from django import forms
from .models import Reservation
from django.contrib.auth.models import User

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['user', 'check_in', 'check_out', 'room_number']  # user alanını ekle

Django projet 3/myapp2/app1/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import ReservationForm
from .models import Reservation
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, "index.html")
def user_login(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login (request,user)
            return render(request,"index.html")
        else:
            return render(request,"login.html",{"error":"username ya da parola yanlış girilmiştir"})
    else:
        return render(request,"login.html")
    
def room(request):
    return render(request,"reservation_list.html")
       

def room1(request):
    return render(request,"Luxury_Suite.html")
def room2(request):
    return render(request,"Delux_Suite.htmll")
def room3(request):
    return render(request,"Premier_Suite.htmll")
def room4(request):
    return render(request,"Luxury_Room.html")
def room5(request):
    return render(request,"Delux_Room.html")
def room6(request):
    return render(request,"Premier_Room.html")


def user_register(request):
    if request.method=="POST":
        username=request.POST["username"]
        email=request.POST["email"]
        password=request.POST["password"]
        repassword=request.POST["repassword"]

        if password == repassword:
            if User.objects.filter(username=username).exists():
                return render(request,"login.html",{"error":"username kullanılıyor.."})
            else:
                if User.objects.filter(email=email).exists():
                    return render(request,"login.html",{"error":"bu email adresinden önceden kayıt yapılmıştır.."})
                else:
                    user=User.objects.create_user(username=username,email=email,password=password)
                    user.save()
                    return render(request,"login.html") #bu yönlendirme değiştirilmiştir
        else:
            return render(request,"login.html",{"error":"parolayı yanlış ya da eksik tuşladınız"})
    else:
        return render(request,"login.html")
def create_reservation(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user  # Kullanıcıyı ilişkilendir
            reservation.save()  # Veritabanına kaydet
            messages.success(request, 'Rezervasyon başarıyla oluşturuldu.')
            return redirect('home')  # Başka bir sayfaya yönlendirme
        else:
            messages.error(request, 'Formda hata var, lütfen kontrol edin.')
    else:
        form = ReservationForm()

    return render(request, 'index.html', {'form': form})  # Formu render et
            
def reservation_list(request):
    reservations=Reservation.objects.filter(user=request.user)
    return render(request,'reservation_list.html',{'reservations':reservations})

def cancel_reservation(request, reservation_id):
    reservation=Reservation.objects.get(id=reservation_id,user=request.user)
    if reservation:
        reservation.delete()
        messages.success(request,'Rezarvosyonunuz Başarılı Bir Şekilde İptal Edildi..')

    else:
        messages.error(request,'Rezervasyonununuz Bulunmadı..')
    return redirect('reservation_list')
    

Django projet 3/myapp2/app1/templates/Luxury_Suite.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Magestic Hotel</title>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'dist/slick.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/jquery.scrollUp.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dist/style1.js' %}">
    <script type="text/javascript" src="{% static 'dist/demo.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <style>
        .tm-roomsection {
            display: flex;
            justify-content: center; /* Yatay ortalama */
            align-items: center; /* Dikey ortalama */
            flex-direction: column; /* Dikey hizalama için sütun düzeni */
            height: 100vh; /* Tüm ekran yüksekliği */
        }
        .tm-roomimage {
            margin: 20px 0; /* Resim etrafında boşluk */
        }
        .tm-resbutton {
            margin-top: 20px; /* Rezervasyon butonu için boşluk */
        }
    </style>
</head>

<body>
    <header class="tm-header">
        <header class="tm-header">
            <img class="tm-logo" src="{% static 'img/hotel.png' %}" style="width: 50px; height: 50px; position: absolute; left: 5;">
                </header>
        <nav class="tm-nav">
                <label for="menu-toggle" class="menu-icon">&#9776;</label>
                <ul>
                    <ul class="menu">
                        <li class="tm-list"><a href="login.html">Anasayfa</a></li>
                        <li class="tm-list"><a href="explore.html">Keşfetmek</a></li>
                        <li class="tm-list"><a href="rooms.html">Odalarımız</a></li>
                        <li class="tm-list"><a href="rezervasyon_oluştur">Rezervasyon</a></li>
                        <li class="tm-list"><a href="contact.html">İletişim</a></li>
                        <li class="tm-list dropdown">
                            <a href="login.html">Çıkış Yap</a>
                            <ul class="dropdown-content">
                                <a href="profile.html">Profil</a>
                                <a href="settings.html">Ayarlar</a>
                                <a href="login.html">Çıkış</a>
                            </ul>
                        </li>
                    </ul>
                </ul>
        </nav>
    </header>
    </header>

    <section class="tm-main" style="padding: 1px; margin: 0px; background-color: rgb(34, 47, 110);">
        <p style="font-size: 30px;">Luxury Suite</p>
    </section>

    <section class="tm-roomsection">
        <div class="tm-room1">
           

           
                <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 000900.jpg' %}" style="width: 580px; height: 400px;">
            

            
                <div class="create">
                    <form method="POST" action="{% url 'create_reservation' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label  for="id_check_in">Giriş Tarihi:</label>
                            <input style="padding: 1px; margin: 0px; color: rgb(34, 47, 110);" type="date" id="id_check_in" name="check_in" required>
                        </div>
            
                        <div class="form-group">
                            <label for="id_check_out">Çıkış Tarihi:</label>
                            <input style="padding: 1px; margin: 0px; color: rgb(34, 47, 110);" type="date" id="id_check_out" name="check_out" required>
                        </div>
            
                        <div class="form-group">
                            <label for="id_room_number">Oda Numarası:</label>
                            <input style="padding: 1px; margin: 0px; color: rgb(34, 47, 110);" type="number" id="id_room_number" name="room_number" min="1" required>
                        </div>
            
                        <section class="tm-makeres">
                            <div class="tm-res" style="text-align: center;">
                                <form method="POST" action="{% url 'home' %}">
                                    {% csrf_token %}
                                    <div class="tm-resbutton" style="display: inline-block;">
                                        <button  type="submit" class="reservation-btn">
                                            <p>Rezervasyon Yap</p>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </form>
                </div>

            
            
        </div>
    </section>
</body>
</html>

Django projet 3/myapp2/app1/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Magestic Hotel</title>
    
    <title>Majestic Hotel</title>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script><!--düzeltme yaptım dikkat et-->
    <script type="text/javascript" src="{% static 'dist/slick.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/jquery.scrollUp.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dist/style1.js' %}">
    <script type="text/javascript" src="{% static 'dist/demo.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    


</head>

<body>
    
    <header class="tm-header">
        <header class="tm-header">
        <img class="tm-logo" src="{% static 'img/hotel.png' %}" style="width: 50px; height: 50px; position: absolute; left: 5;">
            </header>
        <nav class="tm-nav">
                <label for="menu-toggle" class="menu-icon">&#9776;</label>
                <ul>
                    <ul class="menu">
                        <li class="tm-list"><a href="">Anasayfa</a></li>
                        <li class="tm-list"><a href="explore.html">Keşfetmek</a></li>
                        <li class="tm-list"><a href="rooms.html">Odalarımız</a></li>
                        <li class="tm-list"><a href="room">Rezervasyon</a></li>
                        <li class="tm-list"><a href="contact.html">İletişim</a></li>
                        <li class="tm-list dropdown">
                            <a href="login.html">Çıkış Yap</a>
                            <ul class="dropdown-content">
                                <a href="profile.html">Profil</a>
                                <a href="settings.html">Ayarlar</a>
                                <a href="login.html">Çıkış</a>
                            </ul>
                        </li>
                    </ul>
                </ul>
        </nav>
    </header>
    
    


    <section class="slider room flex">
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 000900.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p class="s">Lüks Süit</p></a>
        </div>
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 001507.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p class="s">Deluxe Süit</p></a>
        </div>
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 001617.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p>Premier Süit</p></a>
        </div>
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 000900.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p class="s">Lüks Oda</p></a>
        </div>
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 001507.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p>Deluxe Oda</p></a>
        </div>
        <div class="tm-rooms">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 001617.jpg' %}" style="width: 580px; height: 400px;">
            <a href="rooms.html"><p>Premier Oda</p></a>
        </div>
    </section>

    <section class="tm-servicesection">
        
        <div class="tm-service">
            <img src="{% static 'img/Ekran görüntüsü 2024-10-18 002754.jpg' %}"  height="250">
            <div>
                <p class="b">Oda Servisi</p>
                <p>Mükemmel ve zamanında oda servisiyle konaklamanızın tadını çıkarın</p>
            </div>
        </div>
        <div class="tm-service">
            <img src="{% static 'img/KAHVALTI.jpg' %}"  height="250">
            <div>
                <p class="b">Ücretsiz Kahvaltı</p>
                <p>Her sabah ücretsiz kahvaltının tadını çıkarın</p>
            </div>
        </div>
    </section>

    <section class="tm-servicesection">
        <div class="tm-service">
            <img src="{% static 'img/PARKalanı.jpg' %}"  height="250">
            <div>
                <p class="b">Ücretsiz Park Alanı</p>
                <p>Aracınızı park etmek için ekstra ücret ödemenize gerek yok</p>
            </div>
        </div>
        <div class="tm-service">
            <img src="{% static 'img/SPA.jpg' %}"  height="250">
            <div>
                <p class="b">Ücretsiz Spa</p>
                <p>Konaklamanız boyunca her gün bir kez tesis bünyesindeki Spa'da rahatlayın
                </p>
            </div>
        </div>
    </section>

    <section class="tm-reviewsection">
        <div class="tm-review">
            <div class="slider review">
                <div class="tm-revcon">
                    <p class="b">Gözden Geçirmek</p>
                    <div class="tm-stars">
                    </div>
                    <div class="tm-rev">
                        <p>Harika bir otel, herkese tavsiye ediyorum. Keşke orada birkaç gün daha kalsaydım.</p><br/>
                        <p>Rachel Green  Tripster</p>
                    </div>
                </div>

                <div class="tm-revcon">
                    <p class="b">Gözden Geçirmeks</p>
                    <div class="tm-stars">

                    </div>
                    <div class="tm-rev">
                        <p>Güzel bir otel, harika bir deneyim yaşadım ve birçok olanak var.</p><br/>
                        <p>Ross Geller Visitor</p>
                    </div>
                </div>

                <div class="tm-revcon">
                    <p class="b">Gözden Geçirmek</p>
                    <div class="tm-stars">

                    </div>
                    <div class="tm-rev">
                        <p>
                            Harika bir otel, harika yemekler yeterince söylendi.</p><br/>
                        <p>Joey Tribiani Actor</p>
                    </div>
                </div>

                <div class="tm-revcon">
                    <p class="b">Gözden Geçirmek</p>
                    <div class="tm-stars">

                    </div>
                    <div class="tm-rev">
                        <p>Çok güzel bir otel, spadan keyif aldım ve bir masöz olarak tavsiye ederim.</p><br/>
                        <p>Pheobe Buffay Traveller</p>
                    </div>
                </div>

                <div class="tm-revcon">
                    <p class="b">Gözden Geçirmek</p>
                    <div class="tm-stars">

                    </div>
                    <div class="tm-rev">
                        <p>Bu otelde en iyi zaman geçirdim. Kesinlikle geri döneceğim.</p><br/>
                        <p>Monica Geller Visitor</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    
    <footer class="tm-footer" style="color: red;">
        <p>© 2024 GOLD Otel. Her hakkı saklıdır</p>
    </footer>
    
   

    <script type="text/javascript">
        $(document).ready(function () {
            // Slider configuration
            $('.slider.single').slick({
                dots: true,
                autoplay: true,
                autoplaySpeed: 3000
            });

            $('.slider.review').slick({
                dots: true,
                autoplay: true,
                autoplaySpeed: 3000
            });

            $('.tm-makeres').slick({
                dots: true,
                autoplay: true,
                autoplaySpeed: 3000
            });

            // Spinner buttons
            $('#handleCounter1').handleCounter({
                minimum: 1,
                maximize: 100,
            });

            $('#handleCounter2').handleCounter({
                minimum: 1,
                maximize: 100,
            });

            // Datepicker
            pickmeup('.range', {
                mode: 'range',
                separator: ' to ',
                position: 'bottom',
                format: 'd b-y',
            });

            // Scroll to top
            $.scrollUp({
                scrollName: 'scrollUp', // Element ID
                topDistance: '600', // Distance from top before showing element (px)
                topSpeed: 300, // Speed back to top (ms)
                animation: 'fade', // Fade, slide, none
                animationInSpeed: 500, // Animation in speed (ms)
                animationOutSpeed: 500, // Animation out speed (ms)
                scrollText: '^',
                activeOverlay: false, // Set CSS color to display scrollUp active point, e.g '#00FFFF'
            });
        });

        // Map function
        function initMap() {
            var uluru = { lat: 19.735121, lng: -155.014044 };
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 14,
                center: uluru
            });
            var marker = new google.maps.Marker({
                position: uluru,
                map: map
            });
        }
    </script>
</body>
</html>

Django projet 3/myapp2/app1/templates/login.html

<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="static/css/style.css"> <!-- Düzeltme burada -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>  
	<link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'> 
	<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form method="post" action="{% url 'user_register' %}">

					{% csrf_token %}
					{% if error %}
						<div class="alert alert-danger">
						{{error}}
						</div>
					{% endif %}
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="username" id="username" placeholder="Username" required>
					<input type="email" name="email" id="email" placeholder="Email" required>
					<input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
					<input type="password" name="repassword" id="repassword" class="form-control" placeholder="Repassword">
					<button type="submit" onclick="window.location.href='kayıt'">Register</button>
				</form>
			</div>

			<div class="login">
				<form method="post" action="{% url 'user_login' %}"><!--dor yapısını unutma-->
					{% csrf_token %}
					{% if error %}
						<div class="alert alert-danger">
						{{error}}
						</div>
					{% endif %}
					<label for="chk" aria-hidden="true">Login</label>
					<input type="text" name="username" id="username" class="form-control" placeholder="Username" required>
					<input type="email" name="email" id="email" placeholder="Email" required>
					<input type="password" name="password" id="password" class="form-control" placeholder="password" required/>
					<button type="submit">LOGIN</button> 
				</form>
			</div>
	</div>
</body>
</html>

Django projet 3/myapp2/app1/templates/reservation_list.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title> Magestic Hotel</title>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script><!--düzeltme yaptım dikkat et-->
    <script type="text/javascript" src="{% static 'dist/slick.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/jquery.scrollUp.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style4.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dist/style1.js' %}">
    <script type="text/javascript" src="{% static 'dist/demo.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    
    </head>
    
<body>
    <header class="tm-header">
        <header class="tm-header">
            <img class="tm-logo" src="{% static 'img/hotel.png' %}" style="width: 50px; height: 50px; position: absolute; left: 5;">
                </header>
        <nav class="tm-nav">
                <label for="menu-toggle" class="menu-icon">&#9776;</label>
                <ul>
                    <ul class="menu">
                        <li class="tm-list"><a href="login.html">Anasayfa</a></li>
                        <li class="tm-list"><a href="explore.html">Keşfetmek</a></li>
                        <li class="tm-list"><a href="rooms.html">Odalarımız</a></li>
                        <li class="tm-list"><a href="rezervasyon_oluştur">Rezervasyon</a></li>
                        <li class="tm-list"><a href="contact.html">İletişim</a></li>
                        <li class="tm-list dropdown">
                            <a href="login.html">Çıkış Yap</a>
                            <ul class="dropdown-content">
                                <a href="profile.html">Profil</a>
                                <a href="settings.html">Ayarlar</a>
                                <a href="login.html">Çıkış</a>
                            </ul>
                        </li>
                    </ul>
                </ul>
        </nav>
    </header>
    
    
    <section class="tm-main" >
        <p >Rooms</p>
    </section>
    
    
      <section class="tm-roomsection">
                    
                    <div class="tm-room1">
                        <div class="tm-trans"> 
                            <div href="rezervasyon_oluştur">
                                <p>2 Bed</p><p>Complimentary liquor</p><p>Free Wifi</p> 
                            </div>
                        <div><p>Only for</p><p class="bold">$ 1999.99</p> </div></div>
                        
                        
                        <a href="room1">
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 000900.jpg' %}" style="width: 580px; height: 400px;">
                        </a>
                        
                     <p class="s">Luxury Suite</p>

                    </div>
                        <div class="tm-room1">
                            <div class="tm-trans"> <div><p>2 Bed</p><p>Luxorious interior</p><p>Free Wifi</p> </div>
                        
                        <div><p>Only for</p><p class="bold">$ 1599.99</p> </div></div>
                    
                        <a href="room2">    
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 001507.jpg' %}"  style="width: 580px; height: 400px;">
                        </a>
                            <p>Delux Suite</p>

                    </div>
                        <div class="tm-room1">
                            
                            <div class="tm-trans"> <div><p>2 Bed</p><p>Scenic View</p><p>Free Wifi</p> </div>
                        
                        <div><p>Only for</p><p class="bold">$ 1299.99</p> </div></div>
                        
                        <a href="room3">    
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 001617.jpg' %}"  style="width: 580px; height: 400px;">
                        </a>
                            <p>Premier Suite</p>

                    </div>
    </section>
    <br/>
     <section class="tm-roomsection">
                    <div class="tm-room1">
                        
                        <div class="tm-trans"> <div><p>2 Bed</p><p>Free wifi</p><p>Fresh towels</p> </div>
                        
                        <div><p>Only for</p><p class="bold">$ 999.99</p> </div></div>
                        
                        <a href="room4">
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 000900.jpg' %}"  style="width: 580px; height: 400px;">
                        </a>
                            <p class="s">Luxury Room</p>

                    </div>
                        <div class="tm-room1">
                            
                            <div class="tm-trans"> <div><p>2 Bed</p><p>Fresh towels</p><p>Less costly</p> </div>
                        
                        <div><p>Only for</p><p class="bold">$ 599.99</p> </div></div>
                        
                        <a href="room5">    
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 001507.jpg' %}"  style="width: 580px; height: 400px;">
                    </a>
                            <p>Delux Room</p>

                    </div>
                        <div class="tm-room1">
                            
                            <div class="tm-trans"> <div><p>1 Bed</p><p>Fresh towels</p><p>Less costly</p> </div>
                        
                        <div><p>Only for</p><p class="bold">$ 399.99</p> </div></div>
                        
                        <a href="room6">    
                            <img class="tm-roomimage" src="{% static 'img/Ekran görüntüsü 2024-10-18 001617.jpg' %}"  style="width: 580px; height: 400px;">
                        </a>    
                             <p>Premier Room</p>

                    </div>
    </section>
       <br/>
    
    
    
       
    
    
    <footer class="tm-footer">
        <div class="tm-us">
        <p class="bold">About Us</p>
        <p>We are a part of chain of luxury hotels 
            which extends all over the world. We 
            provide a luxorious stay with various value
            added and free services which will make
            you visit us over and over again.</p>    
        </div>
       
        <div class="tm-address">
        <p class="bold">Address</p>
        <p>415, Park Avenu, Hawai
            Phone : (211) 9275693451
            Email : majestic@info.com</p>    
        </div>
        <br/>


    </footer>
    

    
    </body>
    
</html>
    